# Generated by Django 4.0.6 on 2022-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdicoesComemorativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('resumo', models.CharField(max_length=500)),
                ('data', models.CharField(max_length=10)),
                ('referencia', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Edicao_Come',
                'verbose_name_plural': 'Edicoes_Come',
                'db_table': 'edicao_come',
                'managed': True,
            },
        ),
    ]
