# Generated by Django 4.0.6 on 2022-07-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicoescomemorativas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/edicoes'),
        ),
    ]
