# Generated by Django 4.0.6 on 2022-07-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_capasdoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhatempoIoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=300)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/ioa')),
            ],
            options={
                'verbose_name': 'Linha Tempo Ioa',
                'verbose_name_plural': 'Linhas do Tempo Ioa',
                'db_table': 'linhatempo_ioa',
                'managed': True,
            },
        ),
    ]
