# Generated by Django 4.0.6 on 2022-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_linhatempopresidentes_alter_linhatempoioa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtosRelevantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/atos_relevantes')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ato_Relevante',
                'verbose_name_plural': 'Atos_Relevantes',
                'db_table': 'ato_relevante',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='capasdoe',
            options={'managed': True, 'verbose_name': 'Capa_Doe', 'verbose_name_plural': 'Capas_Doe'},
        ),
        migrations.AlterModelOptions(
            name='linhatempoioa',
            options={'managed': True, 'verbose_name': 'Linhatempo_Ioa', 'verbose_name_plural': 'Linhasdotempo_Ioa'},
        ),
        migrations.AlterModelOptions(
            name='linhatempopresidentes',
            options={'managed': True, 'verbose_name': 'Linhatempo_Presidente', 'verbose_name_plural': 'Linhatempo_Presidentes'},
        ),
        migrations.AlterField(
            model_name='linhatempopresidentes',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/timeline_presidentes'),
        ),
    ]
