# Generated by Django 4.0.6 on 2022-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atosrelevantes_alter_capasdoe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinasdeImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/maquinas_impressao')),
                ('titulo', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
    ]
