# Generated by Django 4.0.6 on 2022-07-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_descricao_maquinasdeimpressao_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinasdeimpressao',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
