# Generated by Django 4.0.6 on 2022-07-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_maquinasdeimpressao_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinasdeimpressao',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
