# Generated by Django 4.0.6 on 2022-07-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_maquinasdeimpressao_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinasdeimpressao',
            name='marca',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
