# Generated by Django 4.0.6 on 2022-07-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_maquinasdeimpressao_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capasdoe',
            name='titulo',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
