# Generated by Django 4.0.6 on 2022-07-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_capasdoe_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capasdoe',
            name='resumo',
            field=models.CharField(max_length=600),
        ),
    ]
