# Generated by Django 4.0.6 on 2022-07-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_capasdoe_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capasdoe',
            name='ano',
            field=models.CharField(max_length=20),
        ),
    ]
