# Generated by Django 4.0.6 on 2022-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_capasdoe_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhatempoioa',
            name='descricao',
            field=models.CharField(max_length=600),
        ),
    ]
