# Generated by Django 4.0.6 on 2022-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_linhatempoioa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhatempoioa',
            name='titulo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
