# Generated by Django 4.0.6 on 2022-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_linhatempoioa_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhatempopresidentes',
            name='nome',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
