# Generated by Django 4.0.6 on 2022-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_linhatempopresidentes_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhatempopresidentes',
            name='nome',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
