# Generated by Django 4.0.6 on 2022-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_atosrelevantes_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atosrelevantes',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
