# Generated by Django 4.0.6 on 2022-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_edicoescomemorativas_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edicoescomemorativas',
            old_name='referencia',
            new_name='nome_prod',
        ),
        migrations.AddField(
            model_name='edicoescomemorativas',
            name='procedencia',
            field=models.CharField(default='', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='edicoescomemorativas',
            name='titulo',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edicoescomemorativas',
            name='resumo',
            field=models.CharField(default='', max_length=600, null=True),
        ),
    ]
