# Generated by Django 4.0.5 on 2022-08-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_banner1_banner2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner1',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='banner2',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='banner1',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner1',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='banner1',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='banner2',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner2',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='banner2',
            name='image4',
        ),
    ]
