# Generated by Django 4.0.5 on 2022-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_image1_banner1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepoimentosServidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('depoimento', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': 'Depoimento_Servidor',
                'verbose_name_plural': 'Depoimentos_Servidores',
                'db_table': 'depoimento_servidor',
                'managed': True,
            },
        ),
    ]
