# Generated by Django 4.0.5 on 2022-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_fotosservidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosservidores',
            name='descricao',
            field=models.CharField(default='', max_length=500),
        ),
    ]
